In [1]:
from hasp.make_pipeline import make_pipeline

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.


In [19]:
from us8kdata.loader import UrbanSound8K 
import numpy as np

In [100]:
data = UrbanSound8K('../hasp/data')
train_fold = [samples for samples in data.fold_audio_generator(fold=[1, 2])]#, 3, 6, 7, 8, 9, 10])]
val_fold = [samples for samples in data.fold_audio_generator(fold=[4])]
test_fold = [samples for samples in data.fold_audio_generator(fold=[5])]


In [117]:
train_y = data.filter_metadata(fold=[1, 2]).classID.values
val_y = data.filter_metadata(fold=[4]).classID
test_y = data.filter_metadata(fold=[5]).classID

In [5]:
pipe = make_pipeline()

In [85]:
np.array(train_fold).shape, np.array(val_fold).shape, np.array(test_fold).shape

/var/folders/wg/1c2nf1g54cb7z215cpx7zwgh0000gn/T/ipykernel_4771/3706076389.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(train_fold).shape, np.array(val_fold).shape, np.array(test_fold).shape


((1761,), (990,), (936,))

In [86]:
train_y.shape, val_y.shape, test_y.shape

((6806,), (990,), (936,))

In [87]:
pipe.fit(np.array(val_fold), val_y)

/var/folders/wg/1c2nf1g54cb7z215cpx7zwgh0000gn/T/ipykernel_4771/1930546800.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  pipe.fit(np.array(val_fold), val_y)


Pipeline(steps=[('preproc',
                 Pipeline(steps=[('mean_mfcc',
                                  FunctionTransformer(func=<function samples_to_mean_mfcc at 0x10f5281f0>,
                                                      kw_args={'fmax': None,
                                                               'fmin': 0.0,
                                                               'hop_length': 128,
                                                               'n_fft': 512,
                                                               'n_mfcc': 20,
                                                               'sr': 16000})),
                                 ('scaler', StandardScaler())])),
                ('model', LogisticRegression())])

In [101]:
train_fold[0][0].shape

()

In [105]:
np.array(train_fold)

/var/folders/wg/1c2nf1g54cb7z215cpx7zwgh0000gn/T/ipykernel_4771/681601338.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(train_fold)


array([array([0.        , 0.        , 0.        , ..., 0.0084844 , 0.00509675,
              0.00079351], dtype=float32)                                     ,
       array([-0.05932979,  0.02658243,  0.07452848, ...,  0.00106818,
              -0.00067143, -0.0020448 ], dtype=float32)               ,
       array([-0.00210584, -0.00119026, -0.00064091, ...,  0.08035769,
               0.06116096,  0.02130257], dtype=float32)               ,
       ...,
       array([-0.02133309, -0.08298236, -0.1794238 , ...,  0.01724348,
               0.07107978,  0.09656351], dtype=float32)               ,
       array([-0.10214857,  0.00882012,  0.22553867, ..., -0.07364341,
              -0.09342001, -0.0992187 ], dtype=float32)               ,
       array([ 0.15891473,  0.11441738,  0.03424281, ..., -0.18143807,
              -0.12961607, -0.10202649], dtype=float32)               ],
      dtype=object)

In [113]:
pipe.predict(test_fold)

array([8, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 4,
       4, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 4, 4, 2, 4, 5, 4, 4, 4, 2, 2,
       5, 2, 4, 4, 4, 1, 1, 1, 4, 4, 2, 2, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 1, 5, 4, 5, 0, 5, 5, 5, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4,
       6, 7, 6, 7, 7, 6, 2, 2, 2, 9, 9, 9, 9, 9, 9, 3, 3, 9, 3, 3, 3, 3,
       3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 9, 9, 9, 9, 4, 9, 3, 3, 3, 3, 3, 3, 7, 7, 6, 4, 4, 4, 2, 2,
       2, 4, 2, 2, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 5, 1,
       7, 7, 0, 9, 2, 9, 2, 2, 9, 3, 3, 7, 9, 9, 9, 9, 9, 9, 9, 2, 2, 9,
       8, 9, 9, 6, 6, 6, 6, 6, 5, 2, 9, 1, 1, 1, 2, 5, 5, 5, 5, 0, 0, 2,
       0, 0, 0, 0, 0, 5, 5, 0, 9, 9, 0, 0, 9, 9, 9, 9, 9, 2, 8, 8, 8, 8,
       8, 8, 8, 8, 5, 8, 8, 8, 9, 9, 7, 5, 9, 9, 9, 9, 3, 3, 2, 3, 3, 3,
       3, 2, 2, 3, 3, 8, 1, 2, 9, 2, 2, 9, 9, 9, 2,

In [115]:
pipe2 = make_pipeline()

In [118]:
pipe2.fit(train_fold, train_y)

Pipeline(steps=[('preproc',
                 Pipeline(steps=[('mean_mfcc',
                                  FunctionTransformer(func=<function samples_to_mean_mfcc at 0x10f5281f0>,
                                                      kw_args={'fmax': None,
                                                               'fmin': 0.0,
                                                               'hop_length': 128,
                                                               'n_fft': 512,
                                                               'n_mfcc': 20,
                                                               'sr': 16000})),
                                 ('scaler', StandardScaler())])),
                ('model', LogisticRegression())])